name: EnhancedAntiSpam
version: 0.5
main: dev.pace.antispam.EnhancedAntiSpam
api-version: 1.13
authors: [Pace]
commands:
  antispam:
    description: Plugin information.
    aliases:
      - enhancedantispam